
# Netlify configuration for React SPA with Vite

# Global build settings
[build]
  publish = "dist"
  command = "npm run build"

# Handle SPA routing - redirect all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set security headers
[[headers]]
  for = "/*"
    [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' https://cdn.gpteng.co;"

# Set proper MIME types
[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.svg"
    [headers.values]
    Content-Type = "image/svg+xml"
